"""Add user-device many-to-many relationship

Revision ID: 34843550e2c9
Revises: 3dfeffe8c8c1
Create Date: 2025-06-24 12:32:50.473271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34843550e2c9'
down_revision = '3dfeffe8c8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_device_association')
    # ### end Alembic commands ###
