"""Add humidity and water alert thresholds to Device

Revision ID: 591e4b8d9e5d
Revises: 7ad44f034673
Create Date: 2025-06-24 15:35:59.920654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591e4b8d9e5d'
down_revision = '7ad44f034673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('humidity_threshold_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humidity_threshold_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alert_on_water', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('alert_on_water')
        batch_op.drop_column('humidity_threshold_high')
        batch_op.drop_column('humidity_threshold_low')

    # ### end Alembic commands ###
