"""Add voltage alert thresholds and status to Device

Revision ID: 5e1919092f21
Revises: dfd9485b330b
Create Date: 2025-06-25 10:24:37.745429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1919092f21'
down_revision = 'dfd9485b330b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voltage_threshold_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voltage_threshold_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voltage_alert_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('voltage_alert_status')
        batch_op.drop_column('voltage_threshold_high')
        batch_op.drop_column('voltage_threshold_low')

    # ### end Alembic commands ###
