"""Add AlertLog table

Revision ID: 7ad44f034673
Revises: 34843550e2c9
Create Date: 2025-06-24 14:00:33.710652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad44f034673'
down_revision = '34843550e2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_log_timestamp'))

    op.drop_table('alert_log')
    # ### end Alembic commands ###
