"""Add alert status fields to Device model

Revision ID: dfd9485b330b
Revises: 591e4b8d9e5d
Create Date: 2025-06-25 09:43:56.552612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd9485b330b'
down_revision = '591e4b8d9e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_alert_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('humidity_alert_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('water_alert_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('water_alert_status')
        batch_op.drop_column('humidity_alert_status')
        batch_op.drop_column('temp_alert_status')

    # ### end Alembic commands ###
